### ISSUE TITLE
I think this is superfluous

### ISSUE THREAD

**Issue by FuRanSuTW** [GCodergr/Audio-Pooling-Unity#1]
In the GetAudioClip method

**List<AudioClip> sublist = new List<AudioClip> ( );
sublist = audioClipTable[tableIndex];**
wantedAudioClip = audioClipTable[tableIndex][selectedAudioClipIndex];

sublist is never used

And thanks your code! learn a lot!

**Comment by GCodergr** [comment]
Thanks for noticing it!

It has been removed.
